<?xml version="1.0" encoding="UTF-8"?><testrun name="UsuarioServiceTest" project="gerenciamento-tarefa" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.melim.gerenciamento_tarefa.service.UsuarioServiceTest" time="0.332" displayname="UsuarioServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.melim.gerenciamento_tarefa.service.UsuarioServiceTest]">
    <testcase name="deveCriarUmUsuario" classname="com.melim.gerenciamento_tarefa.service.UsuarioServiceTest" time="0.31" displayname="deveCriarUmUsuario()" uniqueid="[engine:junit-jupiter]/[class:com.melim.gerenciamento_tarefa.service.UsuarioServiceTest]/[method:deveCriarUmUsuario()]"/>
    <testcase name="naoDeveCriarUmUsuario" classname="com.melim.gerenciamento_tarefa.service.UsuarioServiceTest" time="0.019" displayname="naoDeveCriarUmUsuario()" uniqueid="[engine:junit-jupiter]/[class:com.melim.gerenciamento_tarefa.service.UsuarioServiceTest]/[method:naoDeveCriarUmUsuario()]">
      <failure>org.opentest4j.AssertionFailedError: Expected com.melim.gerenciamento_tarefa.exception.BusinessException to be thrown, but nothing was thrown.&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)&#13;
	at com.melim.gerenciamento_tarefa.service.UsuarioServiceTest.naoDeveCriarUmUsuario(UsuarioServiceTest.java:45)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
